
import React, { useState, useEffect, useRef } from 'react';
import { 
  Search, BookOpen, ChevronLeft, Loader2, Share2, Download, 
  Twitter, Facebook, MessageCircle, Copy, Check, ExternalLink,
  ChevronRight, Info
} from 'lucide-react';
import { motion, AnimatePresence } from 'motion/react';
import { toPng } from 'html-to-image';
import { quranService, Surah, Ayah, Tafseer } from '../services/quranService';

interface KnowledgePageProps {
  onBack: () => void;
  initialSelection?: any;
}

export default function KnowledgePage({ onBack, initialSelection }: KnowledgePageProps) {
  const [surahs, setSurahs] = useState<Surah[]>([]);
  const [selectedSurah, setSelectedSurah] = useState<Surah | null>(null);
  const [ayahs, setAyahs] = useState<Ayah[]>([]);
  const [translations, setTranslations] = useState<string[]>([]);
  const [loading, setLoading] = useState(false);
  const [searchQuery, setSearchQuery] = useState('');
  const [searchResults, setSearchResults] = useState<any[]>([]);
  const [isSearching, setIsSearching] = useState(false);
  const [activeTafseer, setActiveTafseer] = useState<{ ayah: number, data: Tafseer } | null>(null);
  const [isExporting, setIsExporting] = useState(false);
  const [copied, setCopied] = useState(false);

  const exportRef = useRef<HTMLDivElement>(null);

  const ayahRefs = useRef<{ [key: number]: HTMLDivElement | null }>({});

  useEffect(() => {
    const fetchSurahs = async () => {
      const data = await quranService.getSurahs();
      setSurahs(data);
    };
    fetchSurahs();
  }, []);

  useEffect(() => {
    if (initialSelection && surahs.length > 0) {
      const surah = surahs.find(s => s.number === initialSelection.surah);
      if (surah) {
        handleSurahSelect(surah);
      }
    }
  }, [initialSelection, surahs]);

  useEffect(() => {
    if (initialSelection?.ayah && ayahs.length > 0 && !loading) {
      const element = ayahRefs.current[initialSelection.ayah];
      if (element) {
        element.scrollIntoView({ behavior: 'smooth', block: 'center' });
      }
    }
  }, [initialSelection, ayahs, loading]);

  const handleSurahSelect = async (surah: Surah) => {
    if (selectedSurah?.number === surah.number && ayahs.length > 0) return;
    setSelectedSurah(surah);
    setLoading(true);
    setSearchResults([]);
    setActiveTafseer(null);
    try {
      const [ayahData, transData] = await Promise.all([
        quranService.getSurahAyahs(surah.number),
        quranService.getSurahTranslation(surah.number)
      ]);
      setAyahs(ayahData);
      setTranslations(transData);
    } catch (e) {
      console.error(e);
    } finally {
      setLoading(false);
    }
  };

  const handleSearch = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!searchQuery.trim()) return;
    setIsSearching(true);
    const results = await quranService.searchQuran(searchQuery);
    setSearchResults(results);
    setIsSearching(false);
    setSelectedSurah(null);
  };

  const fetchTafseer = async (ayahNumber: number) => {
    if (activeTafseer?.ayah === ayahNumber) {
      setActiveTafseer(null);
      return;
    }
    if (!selectedSurah) return;
    setLoading(true);
    const data = await quranService.getTafseer(selectedSurah.number, ayahNumber);
    if (data) {
      setActiveTafseer({ ayah: ayahNumber, data });
    }
    setLoading(false);
  };

  const exportAsImage = async (ayah: Ayah, translation: string) => {
    if (!exportRef.current) return;
    setIsExporting(true);
    
    // Create a temporary element for export
    const exportEl = document.createElement('div');
    exportEl.style.position = 'fixed';
    exportEl.style.left = '-9999px';
    exportEl.style.width = '600px';
    exportEl.style.padding = '40px';
    exportEl.style.background = '#ffffff';
    exportEl.style.borderRadius = '24px';
    exportEl.style.fontFamily = "'Inter', sans-serif";
    exportEl.style.color = '#141414';
    exportEl.style.textAlign = 'center';
    
    exportEl.innerHTML = `
      <div style="margin-bottom: 24px; opacity: 0.4; font-size: 12px; font-weight: bold; text-transform: uppercase; letter-spacing: 0.1em;">
        Surah ${selectedSurah?.englishName} | Ayah ${ayah.numberInSurah}
      </div>
      <div style="font-family: 'Amiri', serif; font-size: 32px; line-height: 1.8; margin-bottom: 32px; direction: rtl;">
        ${ayah.text}
      </div>
      <div style="font-size: 18px; line-height: 1.6; color: rgba(20, 20, 20, 0.7); font-style: italic;">
        "${translation}"
      </div>
      <div style="margin-top: 40px; padding-top: 24px; border-top: 1px solid rgba(20, 20, 20, 0.1); font-size: 10px; opacity: 0.3; font-weight: bold; text-transform: uppercase; letter-spacing: 0.2em;">
        Generated by Quran Explorer
      </div>
    `;
    
    document.body.appendChild(exportEl);
    
    try {
      const dataUrl = await toPng(exportEl, { quality: 0.95 });
      const link = document.createElement('a');
      link.download = `Ayah-${selectedSurah?.englishName}-${ayah.numberInSurah}.png`;
      link.href = dataUrl;
      link.click();
    } catch (err) {
      console.error('Export failed', err);
    } finally {
      document.body.removeChild(exportEl);
      setIsExporting(false);
    }
  };

  const shareOnSocial = (platform: string, ayah: Ayah, translation: string) => {
    const text = `Surah ${selectedSurah?.englishName} [${selectedSurah?.number}:${ayah.numberInSurah}]: "${translation}"`;
    const url = window.location.href;
    
    let shareUrl = '';
    switch (platform) {
      case 'twitter':
        shareUrl = `https://twitter.com/intent/tweet?text=${encodeURIComponent(text)}&url=${encodeURIComponent(url)}`;
        break;
      case 'facebook':
        shareUrl = `https://www.facebook.com/sharer/sharer.php?u=${encodeURIComponent(url)}&quote=${encodeURIComponent(text)}`;
        break;
      case 'whatsapp':
        shareUrl = `https://api.whatsapp.com/send?text=${encodeURIComponent(text + ' ' + url)}`;
        break;
      case 'copy':
        navigator.clipboard.writeText(text + ' ' + url);
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
        return;
    }
    
    if (shareUrl) {
      window.open(shareUrl, '_blank');
    }
  };

  return (
    <div className="min-h-screen bg-[#f5f5f5] text-[#141414] font-sans">
      {/* Header */}
      <header className="sticky top-0 z-50 bg-white/80 backdrop-blur-md border-b border-[#141414]/5 px-6 py-4">
        <div className="max-w-7xl mx-auto flex items-center justify-between">
          <div className="flex items-center gap-4">
            <button 
              onClick={onBack}
              className="p-2 hover:bg-[#141414]/5 rounded-full transition-all"
            >
              <ChevronLeft className="w-5 h-5" />
            </button>
            <div>
              <h1 className="text-xl font-serif italic">Quran Explorer</h1>
              <p className="text-[10px] font-bold uppercase tracking-widest text-[#141414]/40">Knowledge Base & Tafseer</p>
            </div>
          </div>

          <form onSubmit={handleSearch} className="relative hidden md:block w-96">
            <Search className="absolute left-4 top-1/2 -translate-y-1/2 w-4 h-4 text-[#141414]/40" />
            <input 
              type="text"
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              placeholder="Search Quran..."
              className="w-full pl-12 pr-4 py-2 bg-[#141414]/5 rounded-full border-none focus:ring-2 focus:ring-[#141414]/10 transition-all text-sm"
            />
          </form>

          <div className="flex items-center gap-2">
            <div className="w-8 h-8 bg-[#141414] text-white rounded-full flex items-center justify-center text-xs font-bold">
              KB
            </div>
          </div>
        </div>
      </header>

      <main className="max-w-7xl mx-auto p-6 grid grid-cols-1 lg:grid-cols-12 gap-8">
        {/* Left Sidebar: Surah List */}
        <div className="lg:col-span-4 space-y-4">
          <div className="bg-white rounded-3xl border border-[#141414]/5 shadow-sm overflow-hidden flex flex-col h-[calc(100vh-160px)]">
            <div className="p-6 border-b border-[#141414]/5 bg-[#141414]/[0.02] flex items-center justify-between">
              <h2 className="text-xs font-bold uppercase tracking-widest text-[#141414]/60">Surahs</h2>
              <span className="text-[10px] font-mono text-[#141414]/30">114 Total</span>
            </div>
            <div className="flex-1 overflow-y-auto p-2 custom-scrollbar">
              {surahs.map((surah) => (
                <button
                  key={surah.number}
                  onClick={() => handleSurahSelect(surah)}
                  className={`w-full flex items-center justify-between p-4 rounded-2xl transition-all group ${selectedSurah?.number === surah.number ? 'bg-[#141414] text-white shadow-lg' : 'hover:bg-[#141414]/5'}`}
                >
                  <div className="flex items-center gap-4">
                    <span className={`text-[10px] font-mono w-8 h-8 flex items-center justify-center rounded-full border ${selectedSurah?.number === surah.number ? 'border-white/20' : 'border-[#141414]/10'}`}>
                      {surah.number}
                    </span>
                    <div className="text-left">
                      <p className="text-sm font-medium">{surah.englishName}</p>
                      <p className={`text-[10px] opacity-60 ${selectedSurah?.number === surah.number ? 'text-white/60' : ''}`}>{surah.englishNameTranslation}</p>
                    </div>
                  </div>
                  <div className="text-right">
                    <p className="font-arabic text-lg opacity-80">{surah.name}</p>
                    <p className="text-[8px] uppercase tracking-tighter opacity-40">{surah.numberOfAyahs} Ayahs</p>
                  </div>
                </button>
              ))}
            </div>
          </div>
        </div>

        {/* Main Content: Ayahs */}
        <div className="lg:col-span-8">
          <AnimatePresence mode="wait">
            {isSearching ? (
              <motion.div 
                key="searching"
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                exit={{ opacity: 0 }}
                className="h-[calc(100vh-160px)] flex flex-col items-center justify-center space-y-4"
              >
                <Loader2 className="w-8 h-8 animate-spin text-[#141414]/20" />
                <p className="text-sm text-[#141414]/40 font-mono uppercase tracking-widest">Searching Knowledge Base...</p>
              </motion.div>
            ) : searchResults.length > 0 ? (
              <motion.div 
                key="search-results"
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                className="space-y-4"
              >
                <div className="flex items-center justify-between mb-6">
                  <h3 className="text-xl font-serif italic">Search Results for "{searchQuery}"</h3>
                  <button 
                    onClick={() => setSearchResults([])}
                    className="text-xs font-bold uppercase tracking-widest text-[#141414]/40 hover:text-[#141414]"
                  >
                    Clear Results
                  </button>
                </div>
                <div className="space-y-6 h-[calc(100vh-220px)] overflow-y-auto pr-2 custom-scrollbar">
                  {searchResults.map((match, i) => (
                    <div key={i} className="bg-white p-8 rounded-[2.5rem] border border-[#141414]/5 shadow-sm space-y-6">
                      <div className="flex items-center justify-between">
                        <span className="text-[10px] font-bold uppercase tracking-widest bg-[#141414]/5 px-3 py-1.5 rounded-full">
                          Surah {match.surah.number}: {match.surah.englishName} | Ayah {match.numberInSurah}
                        </span>
                      </div>
                      <p className="text-right font-arabic text-3xl leading-loose text-[#141414]">{match.text}</p>
                      <p className="text-lg text-[#141414]/60 italic leading-relaxed">"{match.text}"</p>
                    </div>
                  ))}
                </div>
              </motion.div>
            ) : selectedSurah ? (
              <motion.div 
                key="surah-content"
                initial={{ opacity: 0, x: 20 }}
                animate={{ opacity: 1, x: 0 }}
                className="space-y-6"
              >
                {/* Surah Header Card */}
                <div className="bg-[#141414] text-white p-10 rounded-[3rem] shadow-2xl relative overflow-hidden">
                  <div className="relative z-10 flex flex-col md:flex-row md:items-end justify-between gap-6">
                    <div>
                      <div className="flex items-center gap-3 mb-4">
                        <span className="text-[10px] font-bold uppercase tracking-[0.2em] bg-white/10 px-3 py-1 rounded-full">Surah {selectedSurah.number}</span>
                        <span className="text-[10px] font-bold uppercase tracking-[0.2em] bg-white/10 px-3 py-1 rounded-full">{selectedSurah.revelationType}</span>
                      </div>
                      <h2 className="text-5xl font-serif italic mb-2">{selectedSurah.englishName}</h2>
                      <p className="text-sm font-medium opacity-60">{selectedSurah.englishNameTranslation} • {selectedSurah.numberOfAyahs} Ayahs</p>
                    </div>
                    <div className="text-right">
                      <p className="text-6xl font-arabic mb-2">{selectedSurah.name}</p>
                    </div>
                  </div>
                  <div className="absolute -bottom-10 -right-10 text-[15rem] font-arabic opacity-5 select-none pointer-events-none">
                    {selectedSurah.name}
                  </div>
                </div>

                {/* Ayahs List */}
                <div className="space-y-6 h-[calc(100vh-360px)] overflow-y-auto pr-2 custom-scrollbar pb-20">
                  {loading ? (
                    <div className="flex flex-col items-center justify-center py-20 space-y-4">
                      <Loader2 className="w-8 h-8 animate-spin text-[#141414]/10" />
                      <p className="text-xs font-mono uppercase tracking-widest text-[#141414]/30">Loading Surah Content...</p>
                    </div>
                  ) : (
                    ayahs.map((ayah, idx) => (
                      <div 
                        key={ayah.number} 
                        ref={el => { ayahRefs.current[ayah.numberInSurah] = el; }}
                        className={`bg-white p-8 rounded-[2.5rem] border border-[#141414]/5 shadow-sm hover:shadow-md transition-all space-y-8 group ${initialSelection?.ayah === ayah.numberInSurah ? 'ring-2 ring-[#141414]/10' : ''}`}
                      >
                        <div className="flex items-center justify-between border-b border-[#141414]/5 pb-6">
                          <div className="flex items-center gap-3">
                            <span className="w-8 h-8 flex items-center justify-center rounded-full bg-[#141414]/5 text-[10px] font-mono font-bold">
                              {ayah.numberInSurah}
                            </span>
                            <span className="text-[10px] font-bold uppercase tracking-widest text-[#141414]/30">Ayah {ayah.numberInSurah}</span>
                          </div>
                          <div className="flex items-center gap-2 opacity-0 group-hover:opacity-100 transition-opacity">
                            <button 
                              onClick={() => exportAsImage(ayah, translations[idx])}
                              className="p-2 hover:bg-[#141414]/5 rounded-full transition-all text-[#141414]/40 hover:text-[#141414]"
                              title="Export as Image"
                            >
                              <Download className="w-4 h-4" />
                            </button>
                            <div className="relative group/share">
                              <button className="p-2 hover:bg-[#141414]/5 rounded-full transition-all text-[#141414]/40 hover:text-[#141414]">
                                <Share2 className="w-4 h-4" />
                              </button>
                              <div className="absolute right-0 bottom-full mb-2 hidden group-hover/share:flex flex-col bg-white border border-[#141414]/10 rounded-2xl shadow-xl p-2 min-w-[140px] z-20">
                                <button onClick={() => shareOnSocial('twitter', ayah, translations[idx])} className="flex items-center gap-3 p-2 hover:bg-[#141414]/5 rounded-xl text-xs font-medium">
                                  <Twitter className="w-3 h-3" /> Twitter
                                </button>
                                <button onClick={() => shareOnSocial('facebook', ayah, translations[idx])} className="flex items-center gap-3 p-2 hover:bg-[#141414]/5 rounded-xl text-xs font-medium">
                                  <Facebook className="w-3 h-3" /> Facebook
                                </button>
                                <button onClick={() => shareOnSocial('whatsapp', ayah, translations[idx])} className="flex items-center gap-3 p-2 hover:bg-[#141414]/5 rounded-xl text-xs font-medium">
                                  <MessageCircle className="w-3 h-3" /> WhatsApp
                                </button>
                                <button onClick={() => shareOnSocial('copy', ayah, translations[idx])} className="flex items-center gap-3 p-2 hover:bg-[#141414]/5 rounded-xl text-xs font-medium">
                                  {copied ? <Check className="w-3 h-3 text-green-500" /> : <Copy className="w-3 h-3" />} 
                                  {copied ? 'Copied!' : 'Copy Link'}
                                </button>
                              </div>
                            </div>
                            <button 
                              onClick={() => fetchTafseer(ayah.numberInSurah)}
                              className={`p-2 rounded-full transition-all flex items-center gap-2 text-xs font-bold uppercase tracking-widest ${activeTafseer?.ayah === ayah.numberInSurah ? 'bg-[#141414] text-white' : 'bg-[#141414]/5 text-[#141414]/40 hover:bg-[#141414]/10'}`}
                            >
                              <Info className="w-4 h-4" />
                              Tafseer
                            </button>
                          </div>
                        </div>

                        <p className="text-right font-arabic text-4xl leading-[2] text-[#141414]">{ayah.text}</p>
                        
                        <div className="space-y-4">
                          <p className="text-[10px] font-bold uppercase tracking-widest text-[#141414]/30">Translation (Sahih International)</p>
                          <p className="text-xl text-[#141414]/80 italic leading-relaxed">"{translations[idx]}"</p>
                        </div>

                        {/* Tafseer Section */}
                        <AnimatePresence>
                          {activeTafseer?.ayah === ayah.numberInSurah && (
                            <motion.div
                              initial={{ opacity: 0, height: 0 }}
                              animate={{ opacity: 1, height: 'auto' }}
                              exit={{ opacity: 0, height: 0 }}
                              className="overflow-hidden"
                            >
                              <div className="mt-8 pt-8 border-t border-[#141414]/5 bg-stone-50/50 -mx-8 px-8 pb-8 rounded-b-[2.5rem]">
                                <div className="flex items-center justify-between mb-6">
                                  <h4 className="text-[10px] font-bold uppercase tracking-widest text-stone-500">Tafseer: {activeTafseer.data.author}</h4>
                                  <button 
                                    onClick={() => setActiveTafseer(null)}
                                    className="text-[10px] font-bold uppercase tracking-widest text-stone-400 hover:text-stone-600"
                                  >
                                    Close
                                  </button>
                                </div>
                                <div 
                                  className="text-sm text-stone-700 leading-relaxed prose prose-stone max-w-none"
                                  dangerouslySetInnerHTML={{ __html: activeTafseer.data.text }}
                                />
                              </div>
                            </motion.div>
                          )}
                        </AnimatePresence>
                      </div>
                    ))
                  )}
                </div>
              </motion.div>
            ) : (
              <motion.div 
                key="empty"
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                className="h-[calc(100vh-160px)] flex flex-col items-center justify-center text-center space-y-8"
              >
                <div className="w-32 h-32 bg-white rounded-[3rem] shadow-xl flex items-center justify-center relative overflow-hidden group">
                  <div className="absolute inset-0 bg-[#141414] scale-0 group-hover:scale-100 transition-transform duration-500 rounded-[3rem]" />
                  <BookOpen className="w-12 h-12 text-[#141414]/10 group-hover:text-white transition-colors relative z-10" />
                </div>
                <div className="max-w-md">
                  <h2 className="text-3xl font-serif italic text-[#141414] mb-4">Explore Divine Wisdom</h2>
                  <p className="text-sm text-[#141414]/40 leading-relaxed">
                    Select a Surah from the library or use the search bar to discover ayahs, translations, and deep commentaries. Share and export your favorite verses as beautiful cards.
                  </p>
                </div>
                <div className="flex flex-wrap justify-center gap-3">
                  {['Al-Fatiha', 'Al-Baqarah', 'Ya-Sin', 'Al-Mulk'].map(name => (
                    <button 
                      key={name}
                      onClick={() => {
                        const s = surahs.find(surah => surah.englishName === name);
                        if (s) handleSurahSelect(s);
                      }}
                      className="px-6 py-3 bg-white border border-[#141414]/5 rounded-full text-xs font-bold uppercase tracking-widest hover:bg-[#141414] hover:text-white transition-all shadow-sm"
                    >
                      {name}
                    </button>
                  ))}
                </div>
              </motion.div>
            )}
          </AnimatePresence>
        </div>
      </main>

      {/* Export Overlay */}
      {isExporting && (
        <div className="fixed inset-0 z-[100] bg-white/90 backdrop-blur-sm flex flex-col items-center justify-center space-y-6">
          <Loader2 className="w-12 h-12 animate-spin text-[#141414]" />
          <p className="text-sm font-mono uppercase tracking-[0.3em] text-[#141414]">Generating Image...</p>
        </div>
      )}

      <style>{`
        .custom-scrollbar::-webkit-scrollbar {
          width: 4px;
        }
        .custom-scrollbar::-webkit-scrollbar-track {
          background: transparent;
        }
        .custom-scrollbar::-webkit-scrollbar-thumb {
          background: rgba(20, 20, 20, 0.05);
          border-radius: 10px;
        }
        .custom-scrollbar::-webkit-scrollbar-thumb:hover {
          background: rgba(20, 20, 20, 0.1);
        }
        @import url('https://fonts.googleapis.com/css2?family=Amiri:ital,wght@0,400;0,700;1,400;1,700&display=swap');
        .font-arabic {
          font-family: 'Amiri', serif;
        }
      `}</style>
    </div>
  );
}
